enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music-Extended]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "inotia00/revanced-patches"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music'"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "inotia00 ReVanced"
arch = "arm64-v8a"
build-mode = "module"

[YouTube-Extended]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube'"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "inotia00 ReVanced"
arch = "arm64-v8a"
build-mode = "module"

[GooglePhotos]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos/"
arch = "arm64-v8a"
build-mode = "module"

